// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aquabliss;

#nullable disable

namespace aquabliss.Migrations
{
    [DbContext(typeof(AquablissDbContext))]
    [Migration("20230301165837_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("aquabliss.Item", b =>
                {
                    b.Property<string>("Item_ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Item_ID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("aquabliss.LogIn", b =>
                {
                    b.Property<string>("Login_ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Login_Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Login_ID");

                    b.ToTable("LogIn");
                });

            modelBuilder.Entity("aquabliss.Order", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Order_Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Total_Price")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Order_ID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("aquabliss.Product", b =>
                {
                    b.Property<string>("Product_ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Product_ID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("aquabliss.User", b =>
                {
                    b.Property<string>("User_ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("User_ID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
